config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  post 'webhook/:store/created_orders', to: 'webhook#created_orders'
  get 'webhook/health_test', to: 'webhook#health_test'

  # Logs
  get '/errors(/:store_sku)', to: 'dashboard#errors', as: :dashboard_errors
  get '/logs', to: 'logs#index'
  get '/logs/errors', to: 'logs#errors'
  get '/logs/changes', to: 'logs#changes'

  # Dashboard
  root to: 'dashboard#index'
  get '/store/:store_sku/:resource(/:product_sku)', to: 'dashboard#show', as: :dashboard_show
  get 'active_sync', to: 'dashboard#active_synchronizer'

  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  protect_from_forgery
  def index
      @store = Store.find_by(sku: ENV['STORE_SKU'])
      @run_syncronizer = RunSyncronizer.last
  end

  def show
    @store = Store.find_by(sku: params[:store_sku])
    @resource = params[:resource]
    @sorting_method = params[:sort_by] || 'sku'
    @categories = categories
    @products = products
    @product = product
  end

  def errors
    @errors =
      File.open("#{Rails.root}/log/#{Rails.env}.log").readlines.select { |x| x.include?('!!!') }
    @store = Store.find_by(sku: params[:store_sku])
    return unless @store

    # @api_products_skus = @store&.api_products&.map { |x| x['sku'] }
    # @api_to_rails_products = @store&.products&.where&.not(sku: @api_products_skus)
    @rails_to_woo_products = @store&.products&.where&.not(sku: @store&.run_syncronizers.last.woo_products_saved&.map { |x| x['sku'] })
  end

  def active_synchronizer
    ApiSynchronizer.perform_async(params[:env], params[:store])
  end

  private

  def attributes
    %i[
      name sku url_external_api url_woocommerce customer_key secret_key metadata
    ]
  end

  def categories
    case @resource
    when 'api'
      @store
      .run_syncronizers.last
      .api_products
        .map { |x| x['clasificadores'] }
        .flatten
        .compact
        .group_by { |x| x['slug'] }
        .map do |slug, api_categories|
          {
            'slug' => slug,
            'name' => api_categories.first['name'],
            'subcategories' => api_categories.map { |x| x['subcategories'] }.flatten.map { |x| x['name'] }.flatten.uniq
          }
        end
    when 'rails'
      @store.products.map do |product|
        product.classifications.as_json(only: %i[name slug], methods: %i[subcategories])
      end
    when 'woocommerce'
      @store.woo_categories.select { |x| x['parent'].zero? }.map do |category|
        {
          'id' => category['id'],
          'name' => category['name'],
          'slug' => category['slug'],
          'products' => category['count'],
          'subcategories' => woo_subcategories(category['id'])
        }
      end
    end.flatten.uniq
  end

  def woo_subcategories(parent_id)
    @store
      .woo_categories
      .select { |x| x['parent'] == parent_id }
      .map { |x| { 'id' => x['id'], 'name' => x['name'], 'slug' => x['slug'], 'products' => x['count'] } }
  end

  def products
    case @resource
    when 'api'
      @store.run_syncronizers.last.api_products
    when 'rails'
      @store.products
    when 'woocommerce'
      @store.run_syncronizers.last.woo_products_saved
    end.sort_by { |product| product[@sorting_method].to_s }
  end

  def product
    case @resource
    when 'api'
      @store.run_syncronizers.last.api_products.find { |x| x['sku'].to_s == params[:product_sku] }
    when 'rails'
      @store.products.find_by(sku: params[:product_sku])
    when 'woocommerce'
      @store.run_syncronizers.last.woo_products_saved.find { |x| x['sku'] == params[:product_sku] }
    end
  end
end

app/views/dashboard/errors.html.erb
<div class="container mt-5">
  <%= link_to '← Go Back', root_path, class: 'btn btn-link' %>
  <h2 class="text-center">Errores</h2>
  <% if @store %>
    <h3>
      Productos de API no guardados en Rails
      <span id="api-to-rails-quantity"></span>
    </h3>
    <ul id="api-to-rails-list">
      <img src="https://upaep.mx/modules/mod_login_ws_id/tmpl/default/images/load.gif" alt="loading..." height=30 id="api-to-rails-loading" />
      <%# @api_to_rails_products.each do |product| %>
        <!-- <li>
          <strong><%# product.sku %></strong>
          <span><%# product.product_error&.api %></span>
        </li> -->
      <%# end %>
    </ul>
    <script>
      document.addEventListener("DOMContentLoaded", () => { 
        fetch('<%= @store.url_external_api %>')
        .then((resp) => resp.json())
        .then((data) => {
          var products = data.items
          var products_skus = products.map((x) => { return x.sku }).flat(1)
          var rails_products = <%= raw @store&.products&.map(&:sku) %>
          var no_loaded_products_skus = products_skus.filter(el => !rails_products.includes(el));
          document.getElementById('api-to-rails-loading').style.display = 'none';
          document.getElementById('api-to-rails-quantity').innerHTML = `(${no_loaded_products_skus.length})`
          no_loaded_products_skus.map((sku) => {
            console.log(sku)
            let node = document.createElement("LI");
            let strong = document.createElement("STRONG");
            let textnode = document.createTextNode(sku);
            strong.appendChild(textnode);
            node.appendChild(strong);
            document.getElementById('api-to-rails-list').appendChild(node)
          })
        })
        .catch((e) => {
          document.getElementById('api-to-rails-list').innerHTML = e
        })
      })
    </script>
    <hr>
    <br>
    <h3>Productos de Rails no guardados en WooCommerce (<%= @rails_to_woo_products.size %>)</h3>
    <ul>
      <% @rails_to_woo_products.map do |product| %>
        <% error_message = product.product_error&.woo || ProductError.create(sku: product.sku, woo: @store.woo_store.post('products', product.as_json_with_attributes)&.parsed_response&.dig('message'))&.woo %>
        <li>
          <strong><%= product.sku %></strong>
          <span><%= error_message %></span>
        </li>
      <% end %>
    </ul>
    <hr>
    <br>
    <h3>Logs</h3>
  <% end %>
  <% @errors.reverse.first(100).each do |line| %>
    <p><%= line %></p>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<div class="fluid-container mt-5">
  <h1 class="text-center">Dashboard</h1>
    <h3 class="text-center mt-5"><%= @store.name %></h3>
    <div class="container-fluid d-flex flex-wrap justify-content-around">
      <%= link_to dashboard_show_path(@store.sku, 'api') do %>
        <div class="card info" style="min-width: 200px; margin: 5px">
          <div class="card-body">
            <div class="card-title info">ApiCategories</div>
            <div class="card-number">
              <%= @store.group_api_categories_by_slug.size %>
            </div>
            <div class="card-title info">ApiProducts</div>
            <div class="card-number">
              <%= @run_syncronizer.api_products.size%>
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to dashboard_errors_path(@store.sku) do %>
        <div class="card info" style="min-width: 200px; margin: 5px">
          <div class="card-body">
            <div class="card-title info">NoLoadedProducts<br>in Rails</div>
              <%= @run_syncronizer.api_products_errors.size%>
            <div class="card-number">
              
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to dashboard_show_path(@store.sku, 'rails') do %>
        <div class="card info" style="min-width: 200px; margin: 5px">
          <div class="card-body">
            <div class="card-title info">RailsCategories</div>
            <div class="card-number">
              <%= @store.classifications.size %>
            </div>
            <div class="card-title info">RailsProducts</div>
            <div class="card-number">
              <%= @store.products.size %>
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to dashboard_errors_path(@store.sku) do %>
        <div class="card info" style="min-width: 200px; margin: 5px">
          <div class="card-body">
            <div class="card-title info">NoLoadedProducts<br>in WooCommerce</div>
              <%= @run_syncronizer.woo_products_saved.size - @store.products.size%>
            <div class="card-number">
              
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to dashboard_show_path(@store.sku, 'woocommerce') do %>
        <div class="card info" style="min-width: 200px; margin: 5px">
          <div class="card-body">
            <div class="card-title info">WooCategories</div>
              <%= @store.parent_woo_categories.size %>
            <div class="card-number">
              
            </div>
            <div class="card-title info">WooProducts</div>
              <%= @run_syncronizer.woo_products_saved.size %>
            <div class="card-number">
              
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to active_sync_path(store: @store.sku, env: 'production'), class: 'btn-sync' do %>
         Ejecutar en Produccion
      <% end %>
      <%= link_to active_sync_path(store: @store.sku, env: 'stage'), class: 'btn-sync' do %>
         Ejecutar en Stage
      <% end %>
    </div>
 
</div>

app/views/dashboard/show.html.erb
<div class="container mt-5">
  <%= link_to '← Go Back', root_path, class: 'btn btn-link' %>
  <h2 class="text-center"><%= @store.name %> (<%= @resource %>)</h2>
  <br/>
  <% if @product %>
    <h3>Product (<%= @product['sku'] %>)</h3>
    <table class="table">
      <tbody>
        <% @product.as_json.map do |key, value| %>
          <tr>
            <th>
              <%= key %>
            </th>
            <td>
              <%= value %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h3>Categories (<%= @categories.size %>)</h3>
    <% if @categories.blank? %>
      <p>No hay categorías aquí</p>
    <% else %>
      <table class="table">
        <thead>
          <% unless @resource.eql?('api') %>
            <th>ID</th>
          <% end %>
          <th>Name</th>
          <% if @resource.eql?('woocommerce') %>
            <th>Products</th>
          <% end %>
          <th>Slug</th>
          <th>Subcategories</th>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <% unless @resource.eql?('api') %>
                <td>
                  <%= category.dig('id') %>
                </td>
              <% end %>
              <td>
                <%= category['name'] %>
              </td>
              <% if @resource.eql?('woocommerce') %>
                <td>
                  <%= category.dig('products') %>
                </td>
              <% end %>
              <td>
                <%= category['slug'] %>
              </td>
              <% if @resource.eql?('woocommerce') %>
                <td>
                  <%= category['subcategories'] %> (<%= category['subcategories']&.size&.to_i %>)
                </td>
              <% else %>
                <td>
                  <%= category['subcategories'] %> (<%= category['subcategories']&.size&.to_i %>)
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    </hr>
    </br>
    <h3>Products (<%= @products.size %>)</h3>
    <% if @products.blank? %>
      <p>No hay productos aquí</p>
    <% else %>
      <table class="table">
        <thead>
          <th>
            <%= link_to dashboard_show_path(@store['sku'], @resource, { sort_by: 'sku' }) do %>
              SKU
              <i class="fa fa-sort-<%= @sorting_method.eql?('sku') ? 'down' : 'up' %>"></i>
            <% end %>
          </th>
          <th>
            <%= link_to dashboard_show_path(@store['sku'], @resource, { sort_by: 'name' }) do %>
              Name
              <i class="fa fa-sort-<%= @sorting_method.eql?('name') ? 'down' : 'up' %>"></i>
            <% end %>
          </th>
          <th>Images</th>
          <th>Variations</th>
          <th>
            Date Created
          </th>
          <th>
            Date Modified
          </th>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td>
                <%= link_to product['sku'], dashboard_show_path(@store['sku'], @resource, product['sku'], { sort_by: 'date_modified' }) %>
              </td>
              <td>
                <%= product['name'] %>
              </td>
              <td>
                <%= product['images']&.size %>
              </td>
              <td>
                <%= product['variations']&.size %>
              </td>
              <td>
                <%= product['date_created'] %>
              </td>
              <td>
                <%= product['date_modified'] %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  <% end %>
</div>